# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 701434395e400cbac3f1654838a21d2415486bf30f13c2ff821803b10e5bdacd2b1bf8105040c66e27dc36de9b257b6a3119fe876cb8a5af856ccb56e6c89125

test:
  secret_key_base: f5666700d799030f6c5f99771b8af84b288cc8966f1165b7c972883b747795c037d542ea6ecc41202e5c4ccb10c7d15ee0d98170592afeabbd33d600f0105cde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
